### PR TITLE
Use flags to trigger behaviour

### LINKED ISSUE #996: [React Editor] Very fast typing may reset the curser and insert text incorrectly
This is extracted from https://github.com/TypeFox/monaco-languageclient/pull/986#issuecomment-3529886336 where it is noted that if you type very fast, the cursor might be reset and the text may be inserted incorrectly. The original issue has been improved a lot upon (thank you!) but it is still possible to hit this - either manually if you try or easily during tests.

editor-issue

I open this bug to keep track of the issue as testing is an important scenario for us.

### PR DESCRIPTION
**Pull request by kaisalmen**
Use flags `reprocessConfig` to trigger a editor config re-processing. This can trigger an on-demand re-processing of the text/model and editor options (test with statemachine react example)
Use `enforceLanguageClientDispose` to dispose the language client on demand: This was moved from the config to the react component as it is only used here.
Debug logging was improved.
This resolves #996

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr yes, forgot to mention. The debug logging is improved (better timestamp and better and more precise messages).

**Comment by kaisalmen** [comment]
A new next release is available (only the component this time):
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.4.0-next.0

**Comment by kaisalmen** [comment]
@martin-fleck-at is this a possible solution for you?

**Comment by martin-fleck-at** [comment]
@kaisalmen I am a bit swamped today. I might have a chance to try this out but I might only be able to have a more detailed look tomorrow. Sorry for the delay!

**Comment by kaisalmen** [comment]
@martin-fleck-at now worries. Take your time. I will wait for you feedback.

**Comment by kaisalmen** [comment]
New next releases are available:
https://www.npmjs.com/package/monaco-languageclient/v/10.4.0-next.1
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.4.0-next.1

File: packages/wrapper-react/src/index.tsx [hunk 1]
```diff
@@ -89,12 +91,9 @@ const stopQueue = () => {
...
 
-const debugLogging = (id: string, useTime?: boolean) => {
-    if (useTime === true) {
-        logger.debug(`${id}: ${Date.now()}`);
-    } else {
-        logger.debug(id);
-    }
+const debugLogging = (id: string) => {
+    const now = new Date(Date.now());
+    logger.debug(`[${now.getMinutes()}:${now.getSeconds()}:${now.getMilliseconds()}]: ${id}`);
```
Comment (martin-fleck-at) [inline packages/wrapper-react/src/index.tsx]: nit: I'm a big fan of this more detailed logging approach but I feel it is a bit uncommon to see the timestamp without the hour and still formatted like a typical time, e.g.:
```
log.js:155 DEBUG [19:0:614]: Adding to queue: editorInit: QUEUE SIZE before: 0
```
Maybe some improvements:
- Add hour 
- Show hours, minutes and seconds with two digits
- Use a `.` separator (as opposed to `:`) between seconds and milliseconds as it is more common

File: packages/wrapper-react/src/index.tsx [hunk 2]
```diff
@@ -22,10 +22,12 @@ export type MonacoEditorProps = {
     onEditorStartDone?: (editorApp?: EditorApp) => void;
     onLanguageClientsStartDone?: (lcsManager: LanguageClientManager) => void;
     onTextChanged?: (textChanges: TextContents) => void;
-    onConfigProcessed?: (editorApp?: EditorApp) => void;
+    onConfigProcessed?: (result: { textUpdated: boolean, modelUpdated: boolean}, editorApp?: EditorApp) => void;
```
Comment (martin-fleck-at) [inline packages/wrapper-react/src/index.tsx]: nit: I think it would be nice to have a type for the result as adopters might use this as well. 
Maybe we could even pack all three properties (including `editorApp`) into the same result type. This way API changes are a little less invasive as the signature does not really change, just the single parameter might have different properties. But this is not really necessary, just an idea.

File: packages/wrapper-react/src/index.tsx [hunk 3]
```diff
@@ -22,10 +22,12 @@ export type MonacoEditorProps = {
...
     onError?: (error: Error) => void;
     onDisposeEditor?: () => void;
     onDisposeLanguageClient?: () => void;
+    toggleReprocessConfig?: boolean;
```
Comment (martin-fleck-at) [inline packages/wrapper-react/src/index.tsx]: nit: By now we got a lot of properties, might be nice to add some documentation to them since not all of them might be super obvious in what they do and what the effects are.

**Review by martin-fleck-at — APPROVED** [review]
I can confirm that issue #996 is resolved for me with that one. I could not longer reproduce the fast typing issue. Great work, thank you very much @kaisalmen!

I did add some minor comments but nothing that should prevent this PR from being merged.

**Comment by kaisalmen** [comment]
@martin-fleck-at thanks for the useful comments. I will incorporate your feedback tomorrow.

File: packages/wrapper-react/src/index.tsx (hunk 1 above)
Comment (kaisalmen) [reply packages/wrapper-react/src/index.tsx]: Yes, you are right. I will fix that with the next commit.

File: packages/wrapper-react/src/index.tsx (hunk 2 above)
Comment (kaisalmen) [reply packages/wrapper-react/src/index.tsx]: Yes, I will add a type and integrate editorApp 👍

File: packages/wrapper-react/src/index.tsx (hunk 3 above)
Comment (kaisalmen) [reply packages/wrapper-react/src/index.tsx]: Good point. Will do.

**Comment by kaisalmen** [comment]
@CGNonofr and @martin-fleck-at I have implemented the review comments. Additionally, I changed `triggerReprocessConfig` to a number. Effectively, the config is only re-processed if you increment it. Also, `enforceLanguageClientDispose` does not lead to restart of the language client as soon as you type something.

New next releases are available:
https://www.npmjs.com/package/monaco-languageclient/v/10.4.0-next.2
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.4.0-next.2
